version: "3.9"
name: sampleapp

services:
  sql:
    container_name: sampleapp-sql
    hostname: sampleapp-sql
    image: mcr.microsoft.com/azure-sql-edge:latest
    environment:
      - SA_PASSWORD=${SA_PASSWORD}
      - ACCEPT_EULA=Y
      - MSSQL_DATA_DIR=/var/opt/mssql/data
      - MSSQL_LOG_DIR=/var/opt/mssql/log
      - MSSQL_BACKUP_DIR=/var/opt/mssql/backup
    ports:
      - 1900:1433
    volumes:
      - sampleapp-sql:/var/opt/mssql
  azurite:
    container_name: sampleapp-azurite
    hostname: sampleapp-azurite
    image: mcr.microsoft.com/azure-storage/azurite:latest
    ports:
      - 11000:10000
      - 11001:10001
      - 11002:10002
    volumes:
      - sampleapp-azurite:/data

volumes:
  sampleapp-sql:
    driver: local
  sampleapp-azurite:
    driver: local